### ISSUE TITLE
Planed features

### ISSUE THREAD

**Issue by badwolfie** [badwolfie/bdwlib#1]
#### Initial build milestones
- [x] Custom data-types and aliases
- [x] Version utilities
- [x] String utilities
- [x] Generic utilities
- [x] Error handling
#### Milestones for v1.0
- [x] Doubly-linked lists
- [x] Singly-linked lists
- [x] Queues
- [x] Stacks
#### Milestones for v1.1
- [ ] Generic array utilities
- [ ] Byte array utilities
#### Milestone for v1.2
- [x] TCP/UDP client
#### Milestone for v1.3
- [x] TCP/UDP server
#### Milestone for v1.4
- [ ] File utilities
#### Milestone for v1.5
- [ ] Thread utilities
#### Milestone for v1.6
- [ ] Binary trees
#### Milestone for v1.7
- [ ] N-ary trees

**_More to be defined...**_
